// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8X20v-ds0qrmAShwafizdAi7hDvKVGQ',
    appId: '1:1072219330481:web:5ebc5ed0d60b5b3503cf90',
    messagingSenderId: '1072219330481',
    projectId: 'eoc-mcg',
    authDomain: 'eoc-mcg.firebaseapp.com',
    storageBucket: 'eoc-mcg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnRkRQJ4nL1f-efrdP4LDe5jTIVwD0Gic',
    appId: '1:1072219330481:android:1addef0a222aa8a003cf90',
    messagingSenderId: '1072219330481',
    projectId: 'eoc-mcg',
    storageBucket: 'eoc-mcg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiw6_Bds3x9pGe6E_ZYfCZ6Tdjfu1hvC8',
    appId: '1:1072219330481:ios:d542256516dfe8cd03cf90',
    messagingSenderId: '1072219330481',
    projectId: 'eoc-mcg',
    storageBucket: 'eoc-mcg.firebasestorage.app',
    iosBundleId: 'com.example.eocmcg',
  );
}
